# Datenanalyse mit SQL & Python - Tag 2: Übungen

**Teil A:** 30-Minuten Refresh & Warm-up mit Fitness-Bookings  
**Teil B:** Fitness-Daten als Transferübung zu Tag 2  
**Ziel:** Erst Tag 1 mit `bookings` wiederholen, dann `HAVING`, `JOIN`, Subqueries und CTEs mit dem Fitness-Datenmodell anwenden.

## Zeitplanung der Übungen

| Teil | Fokus | Geschätzte Zeit |
|---|---|---|
| Teil A | Tag-1-Refresh mit `bookings` | ca. 30 Minuten |
| Teil B | Transferübung zu Tag 2 mit `bookings`, `members`, `classes` | ca. 45-60 Minuten |

Die Zeiten sind Richtwerte für Gruppenarbeit. Schnellere Gruppen können die Reflexionsfragen vertiefen.

# 09:00–09:30 | Tag-1-Refresh mit 'Fitness_bookings'

## Einrichtung & Daten laden

Führe diese Zelle zuerst aus. Sie lädt die Fitness-Daten in eine SQLite-Datenbank.

In [6]:
import sqlite3
from pathlib import Path

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (10, 5)


def find_fitness_dir():
    candidates = [
        Path('course_data/fitness'),
        Path('../course_data/fitness'),
        Path('../Tag 1/course_data/fitness'),
    ]
    for candidate in candidates:
        if (candidate / 'fitness_bookings.csv').exists():
            return candidate
    raise FileNotFoundError('Fitness-Daten wurden nicht gefunden.')

FITNESS_DIR = 'https://raw.githubusercontent.com/chiaoya/Data_to_Decision_with_SQL_Python/refs/heads/main/course_data/fitness/'

fitness_bookings_df = pd.read_csv(FITNESS_DIR + 'fitness_bookings.csv')
fitness_members_df = pd.read_csv(FITNESS_DIR + 'fitness_members.csv')
fitness_classes_df = pd.read_csv(FITNESS_DIR + 'fitness_classes.csv')

conn = sqlite3.connect(':memory:')
fitness_bookings_df.to_sql('bookings', conn, index=False, if_exists='replace')
fitness_members_df.to_sql('members', conn, index=False, if_exists='replace')
fitness_classes_df.to_sql('classes', conn, index=False, if_exists='replace')

print('Geladene Tabellen: bookings, members, classes')

Geladene Tabellen: bookings, members, classes

## Teil A: 30-Minuten Refresh & Warm-up mit Fitness-Bookings (ca. 30 Minuten)

In Teil A arbeitest du **nur mit der Tabelle `bookings`**.

Das ist die Wiederholung von Tag 1:

- `SELECT`
- `WHERE`
- `COUNT`
- `GROUP BY`
- `ORDER BY`
- `LIMIT`

Die Tabelle `bookings` enthält technische IDs:

| Spalte | Bedeutung |
|---|---|
| `booking_id` | eindeutige Buchungs-ID |
| `member_id` | ID des Mitglieds |
| `class_id` | ID des gebuchten Kurses |

**Wichtig:** In Teil A geht es bewusst noch nicht um Namen, Level oder Trainer. Diese Informationen kommen erst später mit `JOIN` dazu.

### Übung A1: Erste Buchungen anzeigen (ca. 3 Minuten)

**Aufgabe:** Zeige alle Spalten aus `bookings` an.

In [7]:
# Aufgabe: Zeige alle Spalten aus bookings an.
query = '''
SELECT *
FROM bookings;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

   booking_id  member_id  class_id
0        3001         10       214
1        3002          1       215
2        3003         15       202
3        3004         11       202
4        3005         12       219
5        3006          6       209
6        3007         15       220
7        3008          9       210
8        3009          5       215
9        3010         19       207

### Übung A2: Nur ausgewählte Spalten anzeigen (ca. 3 Minuten)

**Aufgabe:** Zeige nur `member_id` und `class_id` an.

**Reflexion:** Welche fachlichen Informationen fehlen, wenn wir nur IDs sehen?

In [ ]:
# Aufgabe: Wähle member_id und class_id aus.
query = '''
SELECT _____, _____
FROM bookings;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

### Übung A3: Anzahl aller Buchungen (ca. 3 Minuten)

**Aufgabe:** Wie viele Buchungen gibt es insgesamt?

**Hinweis:** Verwende `COUNT(*)`.

In [ ]:
# Aufgabe: Zähle alle Buchungen.
query = '''
SELECT COUNT(*) AS anzahl_buchungen
FROM _____;
'''

result = pd.read_sql_query(query, conn)
result

### Übung A4: Buchungen eines Mitglieds filtern (ca. 4 Minuten)

**Aufgabe:** Zeige alle Buchungen von Mitglied `15`.

**Hinweis:** Verwende `WHERE member_id = 15`.

In [ ]:
# Aufgabe: Filtere Buchungen von member_id 15.
query = '''
SELECT *
FROM bookings
WHERE _____ = _____;
'''

result = pd.read_sql_query(query, conn)
result

### Übung A5: Buchungen eines Kurses zählen (ca. 4 Minuten)

**Aufgabe:** Wie oft wurde Kurs `202` gebucht?

**Hinweis:** Kombiniere `COUNT(*)` mit `WHERE class_id = 202`.

In [ ]:
# Aufgabe: Zähle Buchungen für class_id 202.
query = '''
SELECT COUNT(*) AS anzahl_buchungen
FROM bookings
WHERE _____ = _____;
'''

result = pd.read_sql_query(query, conn)
result

### Übung A6: Buchungen pro Kurs (ca. 5 Minuten)

**Aufgabe:** Wie viele Buchungen gibt es pro `class_id`?

**Hinweis:** Verwende `GROUP BY class_id`.

In [3]:
# Aufgabe: Berechne Buchungen pro Kurs.
query = '''
SELECT
    class_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY _____
ORDER BY anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

DatabaseError: Execution failed on sql '
SELECT
    class_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY _____
ORDER BY anzahl_buchungen DESC;
': no such column: _____

### Übung A7: Aktivste Mitglieder (ca. 5 Minuten)

**Aufgabe:** Welche fünf Mitglieder haben am häufigsten Kurse gebucht?

**Hinweis:** Gruppiere nach `member_id`, sortiere absteigend und nutze `LIMIT 5`.

In [ ]:
# Aufgabe: Finde die aktivsten Mitglieder nach ID.
query = '''
SELECT
    member_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY _____
ORDER BY _____ DESC
LIMIT _____;
'''

result = pd.read_sql_query(query, conn)
result

### Übung A8: Vorbereitung auf Tag 2 mit HAVING (ca. 3 Minuten)

**Aufgabe:** Welche Kurse wurden mindestens 3-mal gebucht?

**Hinweis:** Diese Aufgabe nutzt bereits `HAVING`, weil die Bedingung auf einer gruppierten Kennzahl liegt.

In [ ]:
# Aufgabe: Nutze HAVING für Kurse mit mindestens 3 Buchungen.
query = '''
SELECT
    class_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY class_id
HAVING _____ >= 3
ORDER BY anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result

## Kurze Reflexion nach Teil A

Diskutiert in der Gruppe:

1. Welche Fragen konnten wir nur mit `bookings` beantworten?
1. Welche Fragen bleiben offen, solange wir nur IDs sehen?
1. Warum brauchen wir für Kursnamen, Trainer oder Mitgliedslevel einen `JOIN`?

# 14:20–15:40 | Praxis mit Day_2_Exercise_Teil B

## Teil B: Fitness-Daten als Transferübung (ca. 45-60 Minuten)

In Teil B arbeitest du weiter mit dem Fitness-Datenmodell:

- `bookings`
- `members`
- `classes`

Die SQL-Logik ist ähnlich wie im Tag-2-Hauptnotebook mit Shop-Daten. Ziel ist, die Konzepte auf ein anderes Datenmodell zu übertragen:

- `HAVING`
- `JOIN`
- einfache Subqueries
- CTEs mit `WITH`
- Primärschlüssel und Fremdschlüssel im Datenmodell erkennen

### Übung B1: Datenmodell verstehen (ca. 5 Minuten)

**Aufgabe:** Schau dir die drei Tabellen kurz an.

**Reflexion:** Welche Spalten sind IDs? Welche IDs verbinden die Tabellen miteinander?

In [ ]:
# Aufgabe: Schaue dir die drei Tabellen kurz an.
print('bookings')
display(pd.read_sql_query('SELECT * FROM bookings LIMIT 5;', conn))

print('members')
display(pd.read_sql_query('SELECT * FROM members LIMIT 5;', conn))

print('classes')
display(pd.read_sql_query('SELECT * FROM classes LIMIT 5;', conn))

### Übung B2: Buchungen pro Mitglied mit HAVING (ca. 5 Minuten)

**Aufgabe:** Welche Mitglieder haben mindestens 3 Buchungen?

**Hinweis:** Die Bedingung bezieht sich auf `COUNT(*)`, also brauchst du `HAVING`.

In [ ]:
# Aufgabe: Filtere Gruppen mit HAVING.
query = '''
SELECT
    member_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY member_id
HAVING _____ >= 3
ORDER BY anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result

### Übung B3: JOIN zwischen Bookings und Members (ca. 6 Minuten)

**Aufgabe:** Zeige `booking_id`, Mitgliedsname und Level.

**Hinweis:** Verbinde `bookings` und `members` über `member_id`.

In [ ]:
# Aufgabe: Verbinde bookings mit members.
query = '''
SELECT
    b.booking_id,
    m.name,
    m.level
FROM bookings AS b
INNER JOIN members AS m
    ON b._____ = m._____
ORDER BY b.booking_id;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

### Übung B4: JOIN mit Tag-1-Aggregation (ca. 6 Minuten)

**Aufgabe:** Wie viele Buchungen gibt es pro Mitgliedslevel?

**Hinweis:** Kombiniere `JOIN`, `GROUP BY`, `COUNT` und `ORDER BY`.

In [ ]:
# Aufgabe: Aggregiere Buchungen pro Level.
query = '''
SELECT
    m.level,
    COUNT(b.booking_id) AS anzahl_buchungen
FROM bookings AS b
INNER JOIN members AS m
    ON b.member_id = m.member_id
GROUP BY _____
ORDER BY _____ DESC;
'''

result = pd.read_sql_query(query, conn)
result

### Übung B5: Bookings und Classes joinen (ca. 6 Minuten)

**Aufgabe:** Zeige `booking_id`, Kursname, Trainerin oder Trainer und Preis.

**Hinweis:** Verbinde `bookings` und `classes` über `class_id`.

In [ ]:
# Aufgabe: Verbinde bookings mit classes.
query = '''
SELECT
    b.booking_id,
    c.class_name,
    c.trainer,
    c.price
FROM bookings AS b
INNER JOIN classes AS c
    ON b._____ = c._____
ORDER BY b.booking_id;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

### Übung B6: Umsatz pro Trainerin oder Trainer (ca. 7 Minuten)

**Aufgabe:** Berechne pro Trainerin oder Trainer die Anzahl der Buchungen und den geschätzten Umsatz.

**Hinweis:** Jede Buchung zählt den Kurspreis einmal. Nutze `SUM(c.price)`.

In [ ]:
# Aufgabe: Berechne Buchungen und Umsatz pro Trainer.
query = '''
SELECT
    c.trainer,
    COUNT(b.booking_id) AS anzahl_buchungen,
    SUM(c.price) AS revenue
FROM bookings AS b
INNER JOIN classes AS c
    ON b.class_id = c.class_id
GROUP BY _____
ORDER BY revenue DESC;
'''

result = pd.read_sql_query(query, conn)
result

### Übung B7: Kurse mit mindestens 3 Buchungen (ca. 7 Minuten)

**Aufgabe:** Zeige Kursname, Trainerin oder Trainer und Buchungsanzahl für Kurse mit mindestens 3 Buchungen.

**Hinweis:** Hier brauchst du `JOIN`, `GROUP BY` und `HAVING`.

In [ ]:
# Aufgabe: Nutze HAVING nach der Gruppierung.
query = '''
SELECT
    c.class_name,
    c.trainer,
    COUNT(b.booking_id) AS anzahl_buchungen
FROM bookings AS b
INNER JOIN classes AS c
    ON b.class_id = c.class_id
GROUP BY c.class_id, c.class_name, c.trainer
HAVING _____ >= 3
ORDER BY anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result

### Übung B8: Vollständige Buchungsübersicht (ca. 6 Minuten)

**Aufgabe:** Erstelle eine Übersicht mit `booking_id`, Mitgliedsname, Level, Kursname, Trainerin oder Trainer und Preis.

**Hinweis:** Dafür brauchst du zwei `INNER JOIN`s.

In [ ]:
# Aufgabe: Verbinde alle drei Fitness-Tabellen.
query = '''
SELECT
    b.booking_id,
    m.name,
    m.level,
    c.class_name,
    c.trainer,
    c.price
FROM bookings AS b
INNER JOIN members AS m
    ON b.member_id = m.member_id
INNER JOIN classes AS c
    ON b.class_id = c.class_id
ORDER BY b.booking_id;
'''

result = pd.read_sql_query(query, conn)
result.head(10)

### Übung B9: Subquery (ca. 8 Minuten)

**Aufgabe:** Finde Mitglieder, die mehr Buchungen haben als der Durchschnitt pro aktivem Mitglied.

**Hinweis:** Die innere Abfrage berechnet zuerst die Buchungsanzahl pro Mitglied.

In [ ]:
# Aufgabe: Nutze eine Unterabfrage für den Durchschnitt.
query = '''
SELECT
    member_id,
    COUNT(*) AS anzahl_buchungen
FROM bookings
GROUP BY member_id
HAVING COUNT(*) > (
    SELECT AVG(buchungsanzahl)
    FROM (
        SELECT COUNT(*) AS buchungsanzahl
        FROM bookings
        GROUP BY member_id
    )
)
ORDER BY anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result

### Übung B10: CTE als Vergleich (ca. 8 Minuten)

**Aufgabe:** Löse B9 noch einmal mit einer CTE.

**Vergleich:** Welche Version ist für dich leichter zu lesen: Subquery oder CTE?

In [ ]:
# Aufgabe: Nutze WITH, um Zwischenergebnisse lesbarer zu machen.
query = '''
WITH member_totals AS (
    SELECT
        member_id,
        COUNT(*) AS anzahl_buchungen
    FROM bookings
    GROUP BY member_id
),
average_total AS (
    SELECT AVG(anzahl_buchungen) AS durchschnitt
    FROM member_totals
)
SELECT
    mt.member_id,
    mt.anzahl_buchungen
FROM member_totals AS mt
CROSS JOIN average_total AS avg_t
WHERE mt.anzahl_buchungen > avg_t.durchschnitt
ORDER BY mt.anzahl_buchungen DESC;
'''

result = pd.read_sql_query(query, conn)
result

## Abschlussreflexion

Diskutiert in der Gruppe:

1. Was war in Teil A reine Tag-1-Wiederholung?
1. Welche Aufgabe in Teil B war ähnlich wie im Shop-Beispiel aus dem Hauptnotebook?
1. Was ist der Unterschied zwischen `WHERE` und `HAVING`?
1. Wann ist eine CTE lesbarer als eine Subquery?

## Musterlösungen

Die folgenden Zellen enthalten vollständige Lösungsmuster. Sie sind bewusst als separater Abschnitt gesammelt, damit die Übungen zuerst selbstständig bearbeitet werden können.

### Lösungen Teil A: Refresh & Warm-up

In [4]:
teil_a_loesungen = {
    'A1': '''SELECT * FROM bookings;''',
    'A2': '''SELECT member_id, class_id FROM bookings;''',
    'A3': '''SELECT COUNT(*) AS anzahl_buchungen FROM bookings;''',
    'A4': '''SELECT * FROM bookings WHERE member_id = 15;''',
    'A5': '''SELECT COUNT(*) AS buchungen_class_202 FROM bookings WHERE class_id = 202;''',
    'A6': '''
        SELECT class_id, COUNT(*) AS anzahl_buchungen
        FROM bookings
        GROUP BY class_id
        ORDER BY anzahl_buchungen DESC;
    ''',
    'A7': '''
        SELECT member_id, COUNT(*) AS anzahl_buchungen
        FROM bookings
        GROUP BY member_id
        ORDER BY anzahl_buchungen DESC;
    ''',
    'A8': '''
        SELECT class_id, COUNT(*) AS anzahl_buchungen
        FROM bookings
        GROUP BY class_id
        HAVING COUNT(*) >= 3
        ORDER BY anzahl_buchungen DESC;
    ''',
}

for name, query in teil_a_loesungen.items():
    print(f'--- {name} ---')
    display(pd.read_sql_query(query, conn).head(10))

--- A1 ---

   booking_id  member_id  class_id
0        3001         10       214
1        3002          1       215
2        3003         15       202
3        3004         11       202
4        3005         12       219
5        3006          6       209
6        3007         15       220
7        3008          9       210
8        3009          5       215
9        3010         19       207

--- A2 ---

   member_id  class_id
0         10       214
1          1       215
2         15       202
3         11       202
4         12       219
5          6       209
6         15       220
7          9       210
8          5       215
9         19       207

--- A3 ---

   anzahl_buchungen
0                50

--- A4 ---

   booking_id  member_id  class_id
0        3003         15       202
1        3007         15       220
2        3018         15       217
3        3044         15       215

--- A5 ---

   buchungen_class_202
0                    3

--- A6 ---

   class_id  anzahl_buchungen
0       215                 8
1       220                 5
2       217                 4
3       207                 4
4       212                 3
5       211                 3
6       209                 3
7       208                 3
8       202                 3
9       219                 2

--- A7 ---

   member_id  anzahl_buchungen
0         11                 6
1          1                 5
2         18                 4
3         15                 4
4          2                 4
5         19                 3
6         12                 3
7          9                 3
8          8                 3
9         20                 2

--- A8 ---

   class_id  anzahl_buchungen
0       215                 8
1       220                 5
2       217                 4
3       207                 4
4       212                 3
5       211                 3
6       209                 3
7       208                 3
8       202                 3

### Lösungen Teil B: Fitness-Daten als Transferübung

In [5]:
teil_b_loesungen = {
    'B2': '''
        SELECT member_id, COUNT(*) AS anzahl_buchungen
        FROM bookings
        GROUP BY member_id
        HAVING COUNT(*) >= 3
        ORDER BY anzahl_buchungen DESC;
    ''',
    'B3': '''
        SELECT b.booking_id, b.member_id, m.name, m.level, b.class_id
        FROM bookings AS b
        INNER JOIN members AS m ON b.member_id = m.member_id;
    ''',
    'B4': '''
        SELECT m.level, COUNT(*) AS anzahl_buchungen
        FROM bookings AS b
        INNER JOIN members AS m ON b.member_id = m.member_id
        GROUP BY m.level
        ORDER BY anzahl_buchungen DESC;
    ''',
    'B5': '''
        SELECT b.booking_id, b.member_id, c.class_name, c.trainer, c.price
        FROM bookings AS b
        INNER JOIN classes AS c ON b.class_id = c.class_id;
    ''',
    'B6': '''
        SELECT c.trainer, COUNT(*) AS anzahl_buchungen, SUM(c.price) AS revenue
        FROM bookings AS b
        INNER JOIN classes AS c ON b.class_id = c.class_id
        GROUP BY c.trainer
        ORDER BY revenue DESC;
    ''',
    'B7': '''
        SELECT c.class_name, COUNT(*) AS anzahl_buchungen
        FROM bookings AS b
        INNER JOIN classes AS c ON b.class_id = c.class_id
        GROUP BY c.class_name
        HAVING COUNT(*) >= 3
        ORDER BY anzahl_buchungen DESC;
    ''',
    'B8': '''
        SELECT b.booking_id, m.name, m.level, c.class_name, c.trainer, c.price
        FROM bookings AS b
        INNER JOIN members AS m ON b.member_id = m.member_id
        INNER JOIN classes AS c ON b.class_id = c.class_id
        ORDER BY b.booking_id;
    ''',
    'B9': '''
        SELECT member_id, COUNT(*) AS anzahl_buchungen
        FROM bookings
        GROUP BY member_id
        HAVING COUNT(*) > (
            SELECT AVG(buchungsanzahl)
            FROM (
                SELECT COUNT(*) AS buchungsanzahl
                FROM bookings
                GROUP BY member_id
            )
        )
        ORDER BY anzahl_buchungen DESC;
    ''',
    'B10': '''
        WITH member_totals AS (
            SELECT member_id, COUNT(*) AS anzahl_buchungen
            FROM bookings
            GROUP BY member_id
        ),
        average_total AS (
            SELECT AVG(anzahl_buchungen) AS durchschnitt
            FROM member_totals
        )
        SELECT mt.member_id, mt.anzahl_buchungen
        FROM member_totals AS mt
        CROSS JOIN average_total AS avg_t
        WHERE mt.anzahl_buchungen > avg_t.durchschnitt
        ORDER BY mt.anzahl_buchungen DESC;
    ''',
}

for name, query in teil_b_loesungen.items():
    print(f'--- {name} ---')
    display(pd.read_sql_query(query, conn).head(10))

--- B2 ---

   member_id  anzahl_buchungen
0         11                 6
1          1                 5
2         18                 4
3         15                 4
4          2                 4
5         19                 3
6         12                 3
7          9                 3
8          8                 3

--- B3 ---

   booking_id  member_id            name         level  class_id
0        3001         10   Julian Becker  Intermediate       214
1        3002          1   Olivia Martin  Intermediate       215
2        3003         15     Marie Klein      Advanced       202
3        3004         11     Lena Schulz  Intermediate       202
4        3005         12    Patrick Wolf      Advanced       219
5        3006          6   Michael Braun      Advanced       209
6        3007         15     Marie Klein      Advanced       220
7        3008          9    Sophie Meyer  Intermediate       210
8        3009          5  Sarah Hoffmann      Advanced       215
9        3010         19   Anna Hartmann      Beginner       207

--- B4 ---

          level  anzahl_buchungen
0  Intermediate                22
1      Advanced                16
2      Beginner                12

--- B5 ---

   booking_id  member_id            class_name trainer  price
0        3001         10      Strength Circuit    Anna     17
1        3002          1   Boxing Conditioning     Max     14
2        3003         15      Beginner Pilates   Julia     10
3        3004         11      Beginner Pilates   Julia     10
4        3005         12      Recovery Stretch     Tom     12
5        3006          6  Stretch and Mobility   Julia     24
6        3007         15        Glute Strength    Anna     26
7        3008          9     Cardio Kickboxing     Tom     13
8        3009          5   Boxing Conditioning     Max     14
9        3010         19     Bodyweight Basics     Tom     15

--- B6 ---

  trainer  anzahl_buchungen  revenue
0     Tom                17      360
1     Max                14      241
2   Julia                10      207
3    Anna                 9      190

--- B7 ---

             class_name  anzahl_buchungen
0   Boxing Conditioning                 8
1        Glute Strength                 5
2     Bodyweight Basics                 4
3  Athletic Performance                 4
4  Stretch and Mobility                 3
5   Kettlebell Training                 3
6    Functional Fitness                 3
7      Beginner Pilates                 3
8      Advanced Pilates                 3

--- B8 ---

,booking_id,name,level,class_name,trainer,price
0,3001,Julian Becker,Intermediate,Strength Circuit,Anna,17
1,3002,Olivia Martin,Intermediate,Boxing Conditioning,Max,14
2,3003,Marie Klein,Advanced,Beginner Pilates,Julia,10
3,3004,Lena Schulz,Intermediate,Beginner Pilates,Julia,10
4,3005,Patrick Wolf,Advanced,Recovery Stretch,Tom,12
5,3006,Michael Braun,Advanced,Stretch and Mobility,Julia,24
6,3007,Marie Klein,Advanced,Glute Strength,Anna,26
7,3008,Sophie Meyer,Intermediate,Cardio Kickboxing,Tom,13
8,3009,Sarah Hoffmann,Advanced,Boxing Conditioning,Max,14
9,3010,Anna Hartmann,Beginner,Bodyweight Basics,Tom,15

--- B9 ---

   member_id  anzahl_buchungen
0         11                 6
1          1                 5
2         18                 4
3         15                 4
4          2                 4
5         19                 3
6         12                 3
7          9                 3
8          8                 3

--- B10 ---

   member_id  anzahl_buchungen
0         11                 6
1          1                 5
2          2                 4
3         15                 4
4         18                 4
5          8                 3
6          9                 3
7         12                 3
8         19                 3