# Datenanalyse mit SQL & Python - Tag 1: SQL-Grundlagen

**Dozentin:** Dr. Chiaoya Chang  
**Dauer:** 6 Stunden = 8 UE je 45 Minuten (09:00 - 16:00, mit Pausen)  
**Zeitaufteilung:** 30% Theorie, 60% Praxis, 10% Diskussion

## Ablauf und Zeitplan

| Zeit | Kursphase | Inhalt |
|---|---|---|
| 09:00–09:30 | Begrüßung & Einführung | Kursziele, Ablauf, Erwartungsklärung, Vorstellungsrunde |
| 09:30–10:30 | Von Business-Problemen zu Daten | Entscheidungsprozess, Workshop & Brainstorming |
| 10:30–11:30 | Datentabellen verstehen | Datenstruktur, Relationen, Business-Fragen |
| 11:30–12:10 | 🍽️ Mittagspause | – |
| 12:10–14:00 | SQL-Grundlagen | `SELECT`, `WHERE`, `GROUP BY`, `ORDER BY`, Aggregationen |
| 14:00–14:20 | ☕ Pause | – |
| 14:20–15:40 | Praktische Übungen | Analyse einer Beispiel-Datenbank (Übungsnotebook) |
| 15:40–16:00 | Ergebnisse & Diskussion | Präsentation, Reflexion, Q&A |

**Hinweis:** Die Zeiten sind Richtwerte – hilfreiche Diskussionen dürfen Blöcke leicht verschieben.

## Zusätzliches Kursmaterial

- [W3Schools SQL Tutorial](https://www.w3schools.com/sql/) - zum Nachlesen, Wiederholen und selbstständigen Üben der SQL-Grundlagen.

# 12:10–14:00 | SQL-Grundlagen

## Einrichtung & Importe

Führe diese Zelle aus, um die benötigten Bibliotheken zu importieren:

In [ ]:
import sqlite3
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Plot-Stil festlegen
sns.set_style('whitegrid')
plt.rcParams['figure.figsize'] = (12, 6)

:

## 1. Einführung in SQL & Datenbanken

SQL (Structured Query Language) wird verwendet, um relationale Datenbanken zu verwalten und abzufragen.

**Grundstruktur einer Abfrage:**
```sql
SELECT column1, column2
FROM table_name
WHERE condition
ORDER BY column1
LIMIT 10;
```

In [10]:
# Verbindung zur SQL-Datenbank im Arbeitsspeicher herstellen
conn = sqlite3.connect(':memory:')

# Bestelldaten direkt von GitHub laden
SHOP_DIR = 'https://raw.githubusercontent.com/chiaoya/Data_to_Decision_with_SQL_Python/refs/heads/main/course_data/shop/'

orders_df = pd.read_csv(SHOP_DIR + 'shop_orders.csv')
customers_df = pd.read_csv(SHOP_DIR + 'shop_customers.csv')

conn = sqlite3.connect(':memory:')
orders_df.to_sql('orders', conn, index=False, if_exists='replace')
customers_df.to_sql('customers', conn, index=False, if_exists='replace')

print('Geladene Tabellen:')
print('orders:   ', orders_df.shape)
print('customers:', customers_df.shape)

Geladene Tabellen:
orders:    (50, 4)
customers: (20, 3)

## 2. SQL-Übungen mit URL-Daten

Wir arbeiten jetzt mit dem DataFrame `df`, der direkt von einer GitHub-URL geladen wurde.
Die Daten wurden zusätzlich als SQL-Tabelle `orders` gespeichert.

**Spalten:**
- `order_id`: Bestellnummer
- `customer_id`: Kundennummer
- `product_id`: Produktnummer
- `quantity`: Bestellmenge

### Übung 1: Alle Bestellungen anzeigen

**Aufgabe:** Schreibe eine SQL-Abfrage, die alle Spalten und alle Zeilen aus `orders` auswählt.

**Hinweis:** Verwende `SELECT * FROM ...`

In [ ]:
# Lösung: Alle Bestellungen anzeigen
query = '''
SELECT *
FROM orders;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

### Übung 2: Nur bestimmte Spalten auswählen

**Aufgabe:** Zeige nur `order_id`, `customer_id` und `quantity` an.

**Hinweis:** Trenne mehrere Spalten mit Kommas.

In [11]:
# Lösung: order_id, customer_id und quantity auswählen
query = '''
SELECT order_id, customer_id, quantity
FROM orders;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

   order_id  customer_id  quantity
0      1001           14         4
1      1002           20         3
2      1003            4         4
3      1004           12         4
4      1005           19         3

### Übung 3: Filtern

**Aufgabe A:** Zeige alle Bestellungen, bei denen die Menge `quantity` mindestens 3 ist.

**Hinweis:** Verwende `WHERE quantity >= 3`.

In [12]:
# Lösung: Bestellungen mit quantity >= 3 anzeigen
query = '''
SELECT *
FROM orders
WHERE quantity >= 3;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

   order_id  customer_id  product_id  quantity
0      1001           14         120         4
1      1002           20         110         3
2      1003            4         105         4
3      1004           12         101         4
4      1005           19         108         3

**Aufgabe B:** Zeige alle Kunden, die älter als 30 Jahre sind.

**Hinweis:** Verwende `WHERE age > 30`.

In [ ]:
# Lösung: Kunden über 30 Jahre anzeigen
query = '''
SELECT name, city
FROM customers
WHERE age > 30
ORDER BY age DESC
'''

result = pd.read_sql_query(query, conn)
display(result.head())

### Übung 4: Aggregatfunktionen nutzen

**Aufgabe:** Berechne:
- die Anzahl aller Bestellungen
- die gesamte bestellte Menge
- die durchschnittliche Menge pro Bestellung

**Hinweis:** Verwende `COUNT(*)`, `SUM(quantity)` und `AVG(quantity)`.

In [13]:
# Lösung: COUNT, SUM und AVG berechnen
query = '''
SELECT
    COUNT(*) AS anzahl_bestellungen,
    SUM(quantity) AS gesamte_menge,
    AVG(quantity) AS durchschnittliche_menge
FROM orders;
'''

result = pd.read_sql_query(query, conn)
display(result)

   anzahl_bestellungen  gesamte_menge  durchschnittliche_menge
0                   50            125                      2.5

### Übung 5: Sortieren und begrenzen

**Aufgabe:** Zeige die 5 größten Bestellungen nach `quantity`, absteigend sortiert.

**Hinweis:** Verwende `ORDER BY quantity DESC LIMIT 5`.

In [ ]:
# Lösung: Top 5 Bestellungen nach Menge anzeigen
query = '''
SELECT *
FROM orders
ORDER BY quantity DESC
LIMIT 5;
'''

result = pd.read_sql_query(query, conn)
display(result)

### Zusatzübung: Bestellungen pro Produkt

**Aufgabe:** Gruppiere die Daten nach `product_id` und berechne pro Produkt die gesamte bestellte Menge.
Sortiere das Ergebnis absteigend nach der gesamten Menge.

**Hinweis:** Verwende `GROUP BY product_id`.

In [ ]:
# Lösung: Gesamtmenge pro product_id berechnen
query = '''
SELECT
    product_id,
    SUM(quantity) AS gesamte_menge
FROM orders
GROUP BY product_id
ORDER BY gesamte_menge DESC;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

## Abschlussbeispiel: Eine neue Tabelle mit `CREATE TABLE` erstellen

Zum Schluss erstellen wir selbst eine kleine Retail-Sales-Tabelle.
Die Tabelle hat 4 Spalten und 30 Zeilen:

- `sale_id`: eindeutige Verkaufsnummer
- `product_category`: Produktkategorie
- `quantity`: verkaufte Menge
- `revenue`: Umsatz in Euro

Danach fügen wir Beispieldaten ein und lesen die Tabelle wieder mit SQL aus.

In [ ]:
# Neue Tabelle retail_sales erstellen
cursor = conn.cursor()

cursor.execute('DROP TABLE IF EXISTS retail_sales')

cursor.execute('''
CREATE TABLE retail_sales (
    sale_id INTEGER PRIMARY KEY,
    product_category TEXT,
    quantity INTEGER,
    revenue REAL
)
''')

retail_sales_data = [
    (1, 'Electronics', 2, 399.98),
    (2, 'Clothing', 5, 124.95),
    (3, 'Home', 3, 89.97),
    (4, 'Sports', 1, 59.99),
    (5, 'Beauty', 4, 79.96),
    (6, 'Electronics', 1, 249.99),
    (7, 'Clothing', 2, 49.98),
    (8, 'Home', 6, 179.94),
    (9, 'Sports', 3, 149.97),
    (10, 'Beauty', 2, 39.98),
    (11, 'Electronics', 3, 599.97),
    (12, 'Clothing', 1, 29.99),
    (13, 'Home', 2, 119.98),
    (14, 'Sports', 4, 199.96),
    (15, 'Beauty', 5, 99.95),
    (16, 'Electronics', 2, 459.98),
    (17, 'Clothing', 6, 179.94),
    (18, 'Home', 1, 34.99),
    (19, 'Sports', 2, 89.98),
    (20, 'Beauty', 3, 54.99),
    (21, 'Electronics', 1, 199.99),
    (22, 'Clothing', 4, 119.96),
    (23, 'Home', 5, 249.95),
    (24, 'Sports', 1, 74.99),
    (25, 'Beauty', 2, 44.98),
    (26, 'Electronics', 4, 799.96),
    (27, 'Clothing', 3, 89.97),
    (28, 'Home', 2, 69.98),
    (29, 'Sports', 5, 249.95),
    (30, 'Beauty', 1, 19.99),
]

cursor.executemany('''
INSERT INTO retail_sales (sale_id, product_category, quantity, revenue)
VALUES (?, ?, ?, ?)
''', retail_sales_data)
conn.commit()

print('Tabelle retail_sales wurde erstellt und mit 30 Zeilen gefüllt.')

query = '''
SELECT *
FROM retail_sales
LIMIT 10;
'''

retail_preview = pd.read_sql_query(query, conn)
display(retail_preview)

summary_query = '''
SELECT
    product_category,
    SUM(quantity) AS total_quantity,
    ROUND(SUM(revenue), 2) AS total_revenue
FROM retail_sales
GROUP BY product_category
ORDER BY total_revenue DESC;
'''

retail_summary = pd.read_sql_query(summary_query, conn)
display(retail_summary)

# 14:00–14:20 | ☕ Pause

# 14:20–15:40 | Praktische Übungen & Day_1_Exercise

## Übungen: SQL mit der Tabelle `retail_sales`

Bearbeite die folgenden Aufgaben mit der Tabelle `retail_sales`.
Schreibe deine SQL-Abfrage jeweils in die Variable `query` und führe die Zelle aus.

### Übung R1: Alle Retail-Sales-Daten anzeigen

**Aufgabe:** Zeige alle Spalten und alle Zeilen aus der Tabelle `retail_sales`.

**Hinweis:** Verwende `SELECT * FROM retail_sales`.

In [ ]:
# TODO: Alle Zeilen aus retail_sales anzeigen
query = None  # Ersetze None durch deine SQL-Abfrage

if query is None:
    print('Bitte schreibe zuerst deine SQL-Abfrage in query.')
else:
    result = pd.read_sql_query(query, conn)
    display(result.head())

### Übung R2: Umsätze über 150 Euro filtern

**Aufgabe:** Zeige alle Verkäufe, bei denen `revenue` größer als 150 ist.

**Hinweis:** Verwende eine `WHERE`-Bedingung.

In [ ]:
# TODO: Verkäufe mit revenue > 150 anzeigen
query = None  # Ersetze None durch deine SQL-Abfrage

if query is None:
    print('Bitte schreibe zuerst deine SQL-Abfrage in query.')
else:
    result = pd.read_sql_query(query, conn)
    display(result.head())

### Übung R3: Top 5 Verkäufe nach Umsatz

**Aufgabe:** Zeige die 5 Verkäufe mit dem höchsten `revenue`.

**Hinweis:** Verwende `ORDER BY revenue DESC` und `LIMIT 5`.

In [ ]:
# TODO: Top 5 Verkäufe nach revenue anzeigen
query = None  # Ersetze None durch deine SQL-Abfrage

if query is None:
    print('Bitte schreibe zuerst deine SQL-Abfrage in query.')
else:
    result = pd.read_sql_query(query, conn)
    display(result)

### Übung R4: Umsatz pro Produktkategorie

**Aufgabe:** Berechne pro `product_category` den gesamten Umsatz und die gesamte verkaufte Menge.
Sortiere das Ergebnis nach Umsatz absteigend.

**Hinweis:** Verwende `GROUP BY product_category`.

In [ ]:
# TODO: Umsatz und Menge pro Kategorie berechnen
query = None  # Ersetze None durch deine SQL-Abfrage

if query is None:
    print('Bitte schreibe zuerst deine SQL-Abfrage in query.')
else:
    result = pd.read_sql_query(query, conn)
    display(result)

### Übung R5: Eigene kleine Tabelle erstellen

**Aufgabe:** Erstelle eine neue Tabelle `store_visits` mit 4 Spalten und füge mindestens 5 Zeilen ein.

Vorgeschlagene Spalten:
- `visit_id`
- `store_city`
- `visitors`
- `sales_count`

**Hinweis:** Verwende `CREATE TABLE`, `INSERT INTO` und danach `SELECT *`.

In [ ]:
# TODO: Erstelle eine eigene Tabelle store_visits und lies sie aus
# 1. DROP TABLE IF EXISTS store_visits
# 2. CREATE TABLE store_visits (...)
# 3. INSERT INTO store_visits (...) VALUES (...)
# 4. SELECT * FROM store_visits

print('Schreibe hier deine CREATE TABLE- und INSERT INTO-Befehle.')

# 15:40–16:00 | Ergebnisse & Diskussion

## Zusammenfassung

Sehr gut! Heute hast du zentrale Konzepte kennengelernt und realitätsnahe Szenarien geübt.

**Nächste Schritte:**
- Wiederhole die Codebeispiele
- Bearbeite die Übungen selbstständig
- Experimentiere mit eigenen Anpassungen
- Stelle Fragen zu unklaren Konzepten

## Lösungen zu den Retail-Sales-Übungen

Hier findest du mögliche Lösungen zu den Übungen R1 bis R5.

### Lösung R1: Alle Retail-Sales-Daten anzeigen

In [ ]:
query = '''
SELECT *
FROM retail_sales;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

### Lösung R2: Umsätze über 150 Euro filtern

In [ ]:
query = '''
SELECT *
FROM retail_sales
WHERE revenue > 150;
'''

result = pd.read_sql_query(query, conn)
display(result.head())

### Lösung R3: Top 5 Verkäufe nach Umsatz

In [ ]:
query = '''
SELECT *
FROM retail_sales
ORDER BY revenue DESC
LIMIT 5;
'''

result = pd.read_sql_query(query, conn)
display(result)

### Lösung R4: Umsatz pro Produktkategorie

In [ ]:
query = '''
SELECT
    product_category,
    SUM(quantity) AS total_quantity,
    ROUND(SUM(revenue), 2) AS total_revenue
FROM retail_sales
GROUP BY product_category
ORDER BY total_revenue DESC;
'''

result = pd.read_sql_query(query, conn)
display(result)

### Lösung R5: Eigene kleine Tabelle erstellen

In [ ]:
cursor.execute('DROP TABLE IF EXISTS store_visits')

cursor.execute('''
CREATE TABLE store_visits (
    visit_id INTEGER PRIMARY KEY,
    store_city TEXT,
    visitors INTEGER,
    sales_count INTEGER
)
''')

store_visits_data = [
    (1, 'Berlin', 120, 35),
    (2, 'Munich', 95, 28),
    (3, 'Hamburg', 80, 22),
    (4, 'Cologne', 70, 19),
    (5, 'Berlin', 140, 42),
]

cursor.executemany('''
INSERT INTO store_visits (visit_id, store_city, visitors, sales_count)
VALUES (?, ?, ?, ?)
''', store_visits_data)
conn.commit()

query = '''
SELECT *
FROM store_visits;
'''

result = pd.read_sql_query(query, conn)
display(result)